import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") || "";
const FROM_EMAIL = Deno.env.get("FROM_EMAIL") || "BeforeSpend Notifications <notifications@beforespend.xyz>";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface EmailPayload {
  to: string;
  type: "login_alert" | "low_balance" | "reminder" | "welcome" | "password_reset" | "monthly_summary";
  userName?: string;
  data?: Record<string, any>;
}

// Brand Tokens & Header SVG Logo Layout (Zero Emojis, Pure Premium Vector Icons)
const BRAND_HEADER_HTML = `
  <div style="background: linear-gradient(135deg, #0E2A47 0%, #061626 100%); padding: 32px 24px; text-align: center; border-radius: 16px 16px 0 0; position: relative;">
    <table align="center" border="0" cellpadding="0" cellspacing="0" style="margin: 0 auto;">
      <tr>
        <td style="vertical-align: middle; padding-right: 12px;">
          <div style="width: 42px; height: 42px; background: linear-gradient(135deg, #00A896 0%, #028072 100%); border-radius: 12px; text-align: center; line-height: 42px; box-shadow: 0 4px 12px rgba(0,168,150,0.3);">
            <span style="color: #ffffff; font-weight: 900; font-size: 24px; font-family: 'Plus Jakarta Sans', Inter, Arial, sans-serif;">B</span>
          </div>
        </td>
        <td style="vertical-align: middle; text-align: left;">
          <span style="color: #ffffff; font-size: 26px; font-weight: 800; font-family: 'Plus Jakarta Sans', Inter, Arial, sans-serif; letter-spacing: -0.5px;">Before<span style="color: #00A896;">Spend</span></span>
          <div style="color: #94A3B8; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 1.5px; margin-top: 2px; font-family: sans-serif;">Plan. Allocate. Protect.</div>
        </td>
      </tr>
    </table>
    
    <!-- Automatic No-Reply Header Badge -->
    <div style="margin-top: 18px; display: inline-block; background-color: rgba(255,255,255,0.08); border: 1px solid rgba(255,255,255,0.15); border-radius: 20px; padding: 4px 14px;">
      <span style="color: #CBD5E1; font-size: 11px; font-weight: 600; font-family: sans-serif; letter-spacing: 0.3px;">AUTOMATED TRANSACTIONAL NOTIFICATION — DO NOT REPLY</span>
    </div>
  </div>
`;

// Standard Brand Footer Layout with No-Reply Disclaimer
const BRAND_FOOTER_HTML = `
  <div style="background-color: #F8FAFC; padding: 24px 28px; border-top: 1px solid #E2E8F0; text-align: center; border-radius: 0 0 16px 16px; font-family: Inter, -apple-system, sans-serif;">
    <p style="color: #475569; font-size: 12px; line-height: 1.5; margin: 0 0 10px 0;">
      <strong>Note:</strong> This is an automated account alert generated by <strong>BeforeSpend Inc.</strong> Please do not reply directly to this message.
    </p>
    <p style="color: #64748B; font-size: 12px; margin: 0 0 12px 0;">
      BeforeSpend Inc. &bull; <a href="https://beforespend.xyz" style="color: #00A896; text-decoration: none; font-weight: 700;">beforespend.xyz</a>
    </p>
    <div style="font-size: 11px; color: #94A3B8;">
      <a href="mailto:support@beforespend.xyz" style="color: #00A896; text-decoration: none;">Contact Support</a> &nbsp;|&nbsp; 
      <a href="https://beforespend.xyz/privacy" style="color: #94A3B8; text-decoration: none;">Privacy Policy</a> &nbsp;|&nbsp; 
      <a href="https://beforespend.xyz/terms" style="color: #94A3B8; text-decoration: none;">Terms of Service</a>
    </div>
  </div>
`;

function getEmailTemplate(payload: EmailPayload): { subject: string; html: string } {
  const { type, userName = "Valued User", data = {} } = payload;

  switch (type) {
    case "login_alert": {
      const { ip = "Unknown IP", device = "Web Browser", timestamp = new Date().toUTCString(), location = "Detected Session" } = data;
      return {
        subject: `Security Alert: New sign-in detected on your BeforeSpend account`,
        html: `
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #E2E8F0; border-radius: 16px; font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; box-shadow: 0 10px 25px rgba(0,0,0,0.05);">
            ${BRAND_HEADER_HTML}
            
            <div style="padding: 36px 32px; color: #0E2A47;">
              <!-- Icon Container -->
              <div style="width: 48px; height: 48px; background-color: #EFF6FF; border: 1px solid #DBEAFE; border-radius: 12px; margin-bottom: 20px; text-align: center; line-height: 48px;">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#2563EB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle;"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
              </div>

              <h2 style="font-size: 22px; font-weight: 800; color: #0E2A47; margin: 0 0 12px 0; letter-spacing: -0.3px;">New Account Sign-in</h2>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 20px;">Hello <strong>${userName}</strong>,</p>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 24px;">We recorded a new successful authentication session for your BeforeSpend account. Here are the security audit details:</p>
              
              <!-- Audit Box -->
              <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-left: 4px solid #00A896; border-radius: 10px; padding: 20px; margin-bottom: 24px;">
                <table style="width: 100%; border-collapse: collapse; font-size: 13px; color: #334155;">
                  <tr><td style="padding: 6px 0; font-weight: 700; color: #64748B; width: 140px;">Device / Browser:</td><td style="font-weight: 600; color: #0E2A47;">${device}</td></tr>
                  <tr><td style="padding: 6px 0; font-weight: 700; color: #64748B;">IP Address:</td><td style="font-family: monospace; font-weight: 700; color: #0E2A47;">${ip}</td></tr>
                  <tr><td style="padding: 6px 0; font-weight: 700; color: #64748B;">Session Location:</td><td style="font-weight: 600; color: #0E2A47;">${location}</td></tr>
                  <tr><td style="padding: 6px 0; font-weight: 700; color: #64748B;">Timestamp:</td><td style="font-weight: 600; color: #0E2A47;">${timestamp}</td></tr>
                </table>
              </div>

              <p style="font-size: 13px; color: #64748B; line-height: 1.6; margin-bottom: 28px;">If this sign-in was initiated by you, no action is required. If you did not perform this login, please reset your password immediately to protect your workspace.</p>

              <div style="text-align: center; margin-bottom: 12px;">
                <a href="https://beforespend.xyz/dashboard" style="background-color: #0E2A47; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 12px; font-weight: 700; font-size: 14px; display: inline-block; box-shadow: 0 4px 12px rgba(14,42,71,0.25);">Manage Account Security</a>
              </div>
            </div>
            ${BRAND_FOOTER_HTML}
          </div>
        `,
      };
    }

    case "low_balance": {
      const { bucketName = "Budget Bucket", currentBalance = "₦0.00", threshold = "₦0.00" } = data;
      return {
        subject: `Low Balance Alert: ${bucketName} balance is below limit`,
        html: `
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #E2E8F0; border-radius: 16px; font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; box-shadow: 0 10px 25px rgba(0,0,0,0.05);">
            ${BRAND_HEADER_HTML}
            
            <div style="padding: 36px 32px; color: #0E2A47;">
              <!-- Danger Warning Icon -->
              <div style="width: 48px; height: 48px; background-color: #FEF2F2; border: 1px solid #FECACA; border-radius: 12px; margin-bottom: 20px; text-align: center; line-height: 48px;">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#DC2626" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle;"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>
              </div>

              <h2 style="font-size: 22px; font-weight: 800; color: #0E2A47; margin: 0 0 12px 0;">Low Bucket Balance Warning</h2>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 20px;">Hello <strong>${userName}</strong>,</p>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 24px;">Your budget allocation target <strong>${bucketName}</strong> has dropped below your configured notification threshold limit.</p>

              <!-- Highlight Metric Card -->
              <div style="background: linear-gradient(135deg, #FEF2F2 0%, #FFF5F5 100%); border: 1px solid #FCA5A5; border-radius: 14px; padding: 24px; text-align: center; margin-bottom: 24px;">
                <div style="font-size: 11px; font-weight: 700; color: #991B1B; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px;">Current Available Balance</div>
                <div style="font-size: 34px; font-weight: 900; color: #DC2626; letter-spacing: -1px; margin-bottom: 8px;">${currentBalance}</div>
                <div style="font-size: 12px; color: #7F1D1D; font-weight: 600;">Configured Threshold Limit: <strong>${threshold}</strong></div>
              </div>

              <p style="font-size: 13px; color: #64748B; line-height: 1.6; margin-bottom: 28px;">To maintain healthy cash flow reserves, you can route a new income deposit into this bucket using the Split Calculator.</p>

              <div style="text-align: center;">
                <a href="https://beforespend.xyz/dashboard" style="background-color: #00A896; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 12px; font-weight: 800; font-size: 14px; display: inline-block; box-shadow: 0 4px 12px rgba(0,168,150,0.25);">Re-allocate Funds Now</a>
              </div>
            </div>
            ${BRAND_FOOTER_HTML}
          </div>
        `,
      };
    }

    case "reminder": {
      const { reminderText = "Scheduled Bill", cost = "Scheduled Amount", dueDate = "Today", period = "monthly" } = data;
      return {
        subject: `Bill Reminder: ${reminderText} is due soon`,
        html: `
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #E2E8F0; border-radius: 16px; font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; box-shadow: 0 10px 25px rgba(0,0,0,0.05);">
            ${BRAND_HEADER_HTML}
            
            <div style="padding: 36px 32px; color: #0E2A47;">
              <!-- Bell Icon Container -->
              <div style="width: 48px; height: 48px; background-color: #F0FDF4; border: 1px solid #BBF7D0; border-radius: 12px; margin-bottom: 20px; text-align: center; line-height: 48px;">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#00A896" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle;"><path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9"></path><path d="M10.3 21a1.94 1.94 0 0 0 3.4 0"></path></svg>
              </div>

              <h2 style="font-size: 22px; font-weight: 800; color: #0E2A47; margin: 0 0 12px 0;">Upcoming Bill / Subscription Reminder</h2>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 20px;">Hello <strong>${userName}</strong>,</p>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 24px;">This is an automated notification to keep you informed of an upcoming recurring bill or subscription deduction:</p>

              <!-- Bill Card -->
              <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 12px; padding: 24px; margin-bottom: 24px;">
                <h3 style="font-size: 18px; font-weight: 800; color: #0E2A47; margin: 0 0 14px 0;">${reminderText}</h3>
                <table style="width: 100%; border-collapse: collapse; font-size: 13px; color: #334155;">
                  <tr><td style="padding: 6px 0; font-weight: 600; color: #64748B;">Scheduled Cost:</td><td style="text-align: right; font-weight: 800; color: #00A896; font-size: 15px;">${cost}</td></tr>
                  <tr><td style="padding: 6px 0; font-weight: 600; color: #64748B;">Due Date:</td><td style="text-align: right; font-weight: 700; color: #0E2A47;">${dueDate}</td></tr>
                  <tr><td style="padding: 6px 0; font-weight: 600; color: #64748B;">Frequency:</td><td style="text-align: right; font-weight: 600; color: #475569; text-transform: capitalize;">${period}</td></tr>
                </table>
              </div>

              <div style="text-align: center;">
                <a href="https://beforespend.xyz/dashboard" style="background-color: #0E2A47; color: #ffffff; text-decoration: none; padding: 14px 28px; border-radius: 12px; font-weight: 700; font-size: 14px; display: inline-block; box-shadow: 0 4px 12px rgba(14,42,71,0.25);">Review All Reminders</a>
              </div>
            </div>
            ${BRAND_FOOTER_HTML}
          </div>
        `,
      };
    }

    case "welcome": {
      return {
        subject: `Welcome to BeforeSpend - Master your financial future`,
        html: `
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #E2E8F0; border-radius: 16px; font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; box-shadow: 0 10px 25px rgba(0,0,0,0.05);">
            ${BRAND_HEADER_HTML}
            
            <div style="padding: 36px 32px; color: #0E2A47;">
              <!-- Welcome Star Icon -->
              <div style="width: 48px; height: 48px; background-color: #F0FDF4; border: 1px solid #BBF7D0; border-radius: 12px; margin-bottom: 20px; text-align: center; line-height: 48px;">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#00A896" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle;"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>
              </div>

              <h2 style="font-size: 22px; font-weight: 800; color: #0E2A47; margin: 0 0 12px 0;">Welcome to BeforeSpend, ${userName}!</h2>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 20px;">Your personal finance workspace is fully initialized. Our core methodology empowers you to split and assign every income deposit into custom budget buckets <em>before</em> any spending occurs.</p>
              
              <!-- Framework Box -->
              <div style="background-color: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 14px; padding: 24px; margin-bottom: 24px;">
                <h4 style="color: #0E2A47; font-size: 15px; font-weight: 800; margin: 0 0 12px 0;">The BeforeSpend Blueprint:</h4>
                <ol style="margin: 0; padding-left: 20px; color: #334155; font-size: 13px; line-height: 1.8;">
                  <li><strong>Plan:</strong> Set allocation percentages for Needs, Savings, Investments, and Wants.</li>
                  <li><strong>Allocate:</strong> Route incoming salary & freelancer deposits using the Split Calculator.</li>
                  <li><strong>Protect:</strong> Monitor low-balance alert thresholds and automated bill reminders.</li>
                </ol>
              </div>

              <div style="text-align: center;">
                <a href="https://beforespend.xyz/dashboard" style="background-color: #00A896; color: #ffffff; text-decoration: none; padding: 16px 32px; border-radius: 12px; font-weight: 800; font-size: 15px; display: inline-block; box-shadow: 0 4px 14px rgba(0,168,150,0.3);">Launch Workspace</a>
              </div>
            </div>
            ${BRAND_FOOTER_HTML}
          </div>
        `,
      };
    }

    case "password_reset": {
      const { resetUrl = "https://beforespend.xyz/login" } = data;
      return {
        subject: `Password Reset Request for your BeforeSpend account`,
        html: `
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #E2E8F0; border-radius: 16px; font-family: Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; box-shadow: 0 10px 25px rgba(0,0,0,0.05);">
            ${BRAND_HEADER_HTML}
            
            <div style="padding: 36px 32px; color: #0E2A47;">
              <!-- Key Lock Icon -->
              <div style="width: 48px; height: 48px; background-color: #EFF6FF; border: 1px solid #DBEAFE; border-radius: 12px; margin-bottom: 20px; text-align: center; line-height: 48px;">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#2563EB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="vertical-align: middle;"><path d="m21 2-2 2m-1.5 1.5L14 9.5m-2.5 2.5a5 5 0 1 1-7.07-7.07 5 5 0 0 1 7.07 7.07Z"></path><path d="M15.5 7.5 18 10l2-2-2.5-2.5"></path></svg>
              </div>

              <h2 style="font-size: 22px; font-weight: 800; color: #0E2A47; margin: 0 0 12px 0;">Reset Your Password</h2>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 20px;">Hello <strong>${userName}</strong>,</p>
              <p style="font-size: 14px; line-height: 1.6; color: #475569; margin-bottom: 24px;">We received a request to update the password associated with your BeforeSpend account. Click the button below to complete password verification:</p>

              <div style="text-align: center; margin-bottom: 28px;">
                <a href="${resetUrl}" style="background-color: #0E2A47; color: #ffffff; text-decoration: none; padding: 16px 32px; border-radius: 12px; font-weight: 800; font-size: 15px; display: inline-block; box-shadow: 0 4px 14px rgba(14,42,71,0.25);">Set New Password</a>
              </div>

              <p style="font-size: 12px; color: #94A3B8; line-height: 1.5;">If you did not initiate this request, you can safely disregard this email. Your password will remain unchanged.</p>
            </div>
            ${BRAND_FOOTER_HTML}
          </div>
        `,
      };
    }

    default: {
      return {
        subject: `Notification from BeforeSpend`,
        html: `
          <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border: 1px solid #E2E8F0; border-radius: 16px; font-family: Inter, sans-serif;">
            ${BRAND_HEADER_HTML}
            <div style="padding: 32px 28px;">
              <p style="color: #0E2A47; font-size: 14px;">Hello ${userName},</p>
              <p style="color: #475569; font-size: 14px;">${data.message || "You have a new update in your BeforeSpend workspace."}</p>
            </div>
            ${BRAND_FOOTER_HTML}
          </div>
        `,
      };
    }
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const payload: EmailPayload = await req.json();

    if (!payload.to) {
      return new Response(JSON.stringify({ error: "Missing recipient email address ('to')" }), {
        status: 400,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { subject, html } = getEmailTemplate(payload);

    if (RESEND_API_KEY) {
      const resendRes = await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${RESEND_API_KEY}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          from: FROM_EMAIL,
          to: [payload.to],
          subject,
          html,
        }),
      });

      const resendData = await resendRes.json();
      if (!resendRes.ok) {
        console.warn("Resend API error:", resendData);
        return new Response(JSON.stringify({ success: false, provider: "resend", error: resendData }), {
          status: resendRes.status,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        });
      }

      return new Response(JSON.stringify({ success: true, provider: "resend", data: resendData }), {
        status: 200,
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    } else {
      console.log(`[Email Simulation] To: ${payload.to} | Subject: ${subject}`);
      return new Response(
        JSON.stringify({
          success: true,
          simulated: true,
          message: "Email generated successfully. Configure RESEND_API_KEY in Supabase secrets to send live emails.",
          subject,
        }),
        {
          status: 200,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message || "Failed to process email request" }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
